// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: medchan.proto

package server

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protocol "hello/protocol"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_medchan_proto protoreflect.FileDescriptor

var file_medchan_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x64, 0x63, 0x68, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x1a, 0x0c, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x52, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x54,
	0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x43, 0x68, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x4d, 0x65, 0x64, 0x54, 0x65,
	0x73, 0x74, 0x2e, 0x4d, 0x65, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x4d, 0x65, 0x64, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x64, 0x43,
	0x68, 0x61, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var file_medchan_proto_goTypes = []interface{}{
	(*protocol.MedChanListReq)(nil), // 0: MedTest.MedChanListReq
	(*protocol.MedChanListRes)(nil), // 1: MedTest.MedChanListRes
}
var file_medchan_proto_depIdxs = []int32{
	0, // 0: serprotoc.MedTestSer.GetMedChanList:input_type -> MedTest.MedChanListReq
	1, // 1: serprotoc.MedTestSer.GetMedChanList:output_type -> MedTest.MedChanListRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_medchan_proto_init() }
func file_medchan_proto_init() {
	if File_medchan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_medchan_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medchan_proto_goTypes,
		DependencyIndexes: file_medchan_proto_depIdxs,
	}.Build()
	File_medchan_proto = out.File
	file_medchan_proto_rawDesc = nil
	file_medchan_proto_goTypes = nil
	file_medchan_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MedTestSerClient is the client API for MedTestSer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MedTestSerClient interface {
	// Sends a greeting
	GetMedChanList(ctx context.Context, in *protocol.MedChanListReq, opts ...grpc.CallOption) (*protocol.MedChanListRes, error)
}

type medTestSerClient struct {
	cc grpc.ClientConnInterface
}

func NewMedTestSerClient(cc grpc.ClientConnInterface) MedTestSerClient {
	return &medTestSerClient{cc}
}

func (c *medTestSerClient) GetMedChanList(ctx context.Context, in *protocol.MedChanListReq, opts ...grpc.CallOption) (*protocol.MedChanListRes, error) {
	out := new(protocol.MedChanListRes)
	err := c.cc.Invoke(ctx, "/serprotoc.MedTestSer/GetMedChanList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedTestSerServer is the server API for MedTestSer service.
type MedTestSerServer interface {
	// Sends a greeting
	GetMedChanList(context.Context, *protocol.MedChanListReq) (*protocol.MedChanListRes, error)
}

// UnimplementedMedTestSerServer can be embedded to have forward compatible implementations.
type UnimplementedMedTestSerServer struct {
}

func (*UnimplementedMedTestSerServer) GetMedChanList(context.Context, *protocol.MedChanListReq) (*protocol.MedChanListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedChanList not implemented")
}

func RegisterMedTestSerServer(s *grpc.Server, srv MedTestSerServer) {
	s.RegisterService(&_MedTestSer_serviceDesc, srv)
}

func _MedTestSer_GetMedChanList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(protocol.MedChanListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedTestSerServer).GetMedChanList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serprotoc.MedTestSer/GetMedChanList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedTestSerServer).GetMedChanList(ctx, req.(*protocol.MedChanListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MedTestSer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serprotoc.MedTestSer",
	HandlerType: (*MedTestSerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMedChanList",
			Handler:    _MedTestSer_GetMedChanList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medchan.proto",
}
